### ISSUE TITLE
get has wrong type signature

### ISSUE THREAD

**Issue by scubamaggo** [TylorS/typed-hashmap#2]
The get function seems to have the wrong signature. The readme specifies it correctly as
`get<K, V>(key: K, map: HashMap<K, V>): V | null`

while the implementation actually has 
`get<K, V>(key: K, map: HashMap<K, V>): K | null`

**Comment by TylorS** [comment]
Yes, you're totally correct. I'll get a fix out soon

**Comment by cbyad** [comment]
This issue haven't been fixed . we get the same signature !! :-(

get<K, V>(key: K, map: HashMap<K, V>): K | null;
get<K, V>(key: K): (map: HashMap<K, V>) => K | null;

**Comment by TylorS** [comment]
Hey @cbyad This package is actually not maintained. If you're in need of a hashmap, the work here was built on and improved here with a great maintainer https://github.com/frptools/collectable

**Comment by cbyad** [comment]
@TylorS Thanks. I used basic ES6 Map instead .
I'll check  [](https://github.com/frptools/collectable) for more complex operations and immutable state.
