### ISSUE TITLE
Question: Integration with Angular2

### ISSUE THREAD

**Issue by RauppRafael** [TylorS/typed-hashmap#4]
Do you have any idea on how to iterate through the HashMap at an Angular 2 HTML template using *ngFor?

Update:
Just figured out, thanks!

**Comment by TylorS** [comment]
Hey @RauupRafael, this project is stable, but not actively maintained - I'll mark it as such soon. This project has been pulled in and greatly improved by the project [collectable](https://github.com/frptools/collectable) which offers many more immutable data structures

**Comment by RauppRafael** [comment]
Nice! Thanks man.
